### PR TITLE
Regions to be an unordered TypeSet

### LINKED ISSUE #314: Regions in record resource are modified on every plan/apply
### Terraform Version
```
Terraform v1.8.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.52.0
+ provider registry.terraform.io/ns1-terraform/ns1 v2.2.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output

```
      ~ regions {
          ~ meta = {
              ~ "georegion" = "EUROPE" -> "US-CENTRAL,US-WEST,US-EAST"
            }
          ~ name = "EU" -> "NA"
        }
      ~ regions {
          ~ meta = {
              ~ "country" = "RU" -> "CA,MX,US"
            }
          ~ name = "EU-RU" -> "NA-US-CA-MX"
        }
      ~ regions {
          ~ meta = {
              ~ "georegion" = "US-CENTRAL,US-WEST,US-EAST" -> "EUROPE"
            }
          ~ name = "NA" -> "EU"
        }
      ~ regions {
          ~ meta = {
              ~ "country" = "CA,MX,US" -> "RU"
            }
          ~ name = "NA-US-CA-MX" -> "EU-RU"
        }
      ~ regions {
          ~ meta = {
              + "georegion" = "SOUTH-AMERICA"
            }
          ~ name = "REST" -> "SA"
        }
      ~ regions {
          ~ meta = {
              ~ "georegion" = "SOUTH-AMERICA" -> null
            }
          ~ name = "SA" -> "REST"
        }
```

### Expected Behavior

Without any change in the config, there shouldn't be any delta shown in the plan.

### Actual Behavior
On every single plan, the order of the regions changes and hence forces us to do an apply. However, after this apply, we still see the same diff.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### PR DESCRIPTION
**Pull request by JanBerktold**
Closes #314

### CODE REVIEW

**Review by fformica — APPROVED** [review]
Hey, thanks for the contribution!

**Comment by JanBerktold** [comment]
My apologies @fformica - I thought this was a draft and wasn't done testing it. 

Thanks for catching the array/Set mishap. My remaining concern is that this code path sets a `[]map[string]interface{}` instead of a `Set` for `regions. I am not familiar enough with TF to know whether it magically translates those under the hood. 

```
		regions := make([]map[string]interface{}, 0, len(r.Regions))
		for _, k := range keys {
		for name, region := range r.Regions {
			newRegion := make(map[string]interface{})
			region := r.Regions[k]
			newRegion["name"] = k
			newRegion["name"] = name
			newRegion["meta"] = region.Meta.StringMap()
			regions = append(regions, newRegion)
		}
		log.Printf("Setting regions %+v", regions)
		err := d.Set("regions", regions)
		if err != nil {
			return fmt.Errorf("[DEBUG] Error setting regions for: %s, error: %#v", r.Domain, err)
		}
```

**Comment by fformica** [comment]
Ah, sorry, we should have a new release soon so I hurried to get this in.
Anyway, it's ok, the slice is converted to a Set internally: https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.24.1/helper/schema/field_writer_map.go#L297

**Comment by JanBerktold** [comment]
Awesome, ty! Thanks for getting this out quickly.

**Pull request merged**
