### PR TITLE
chore(go): Upgrade go version to 1.17

### LINKED ISSUE #169: Support Darwin Arm64 (apple silicon, Mac M1 chip)
Running `terraform init` with this provider present:

```
terraform {
  required_providers {
    ns1 = {
      source = "ns1-terraform/ns1"
    }
  }
}

…etc…
```

I get this output, on an apple M1 mac:

```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/ns1-terraform/ns1 v1.11.0 does not have a package available for your current
│ platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
│ Other versions of this provider may have different platforms supported.
```

I can confirm on the Releases page here: https://github.com/ns1-terraform/terraform-provider-ns1/releases that you haven't built an asset for Darwin Arm64 yet. Please can you do this 🙏

### PR DESCRIPTION
**Pull request by seddarj**
By upgrading the go version, it would allow `goreleaser` to provide releases for the Darwin arm64 architecture and would therefore fix #169.

This has potentially a lot of impact and probably needs to be tested thoroughly.

### CODE REVIEW

**Comment by seddarj** [comment]
@Zach-Johnson or @pcatalini maybe you can chip in here?

**Comment by fpereyrap** [comment]
Hello! this is blocking us a release to prod. any news?

**Comment by pcatalini** [comment]
@seddarj do it's necessary to internalize some libs through the go vendor?

**Comment by seddarj** [comment]
I updated the go version and ran `go mod tidy` and `go mod vendor` as it seems that dependencies are vendored into the repository.

I don't think it's strictly necessary to vendor dependencies into the repo but I was trying to not change too many things at once.

I would really like one of the maintainers to  run the acceptance test suite if any to check that the upgrade did not break anything. The unit tests passing is encouraging though.

**Comment by pcatalini** [comment]
@seddarj I ran the acc tests and there is a test failing, I also tested against the master branch and everything seems correct.
One more thing, AFAIK we don't use vendor modules in this project anymore. we use go modules instead

follow the error bellow

`=== RUN   TestAccRecord_meta
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 17890 [running]:
github.com/terraform-providers/terraform-provider-ns1/ns1.removeEmptyMeta(0xc001359320)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/ns1/resource_record.go:442 +0x119
github.com/terraform-providers/terraform-provider-ns1/ns1.resourceDataToRecord(0xc002a7a380, 0xc0005232d0, 0xc0021537d0, 0x26)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/ns1/resource_record.go:360 +0x1b76
github.com/terraform-providers/terraform-provider-ns1/ns1.RecordCreate(0xc0005232d0, 0x1045c00, 0xc0035902d0, 0x2, 0x18ee040)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/ns1/resource_record.go:453 +0x171
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000512880, 0xc0033d7220, 0xc004781840, 0x1045c00, 0xc0035902d0, 0xfd0d01, 0xc000c14ea8, 0xc000111b60)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000513400, 0xc001c838e8, 0xc0033d7220, 0xc004781840, 0xc0011c3168, 0xc0006837d0, 0xfd3760)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000636008, 0x12ece50, 0xc002574540, 0xc001ed1ce0, 0xc000636008, 0xc002574540, 0xc000fe8a50)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10d4660, 0xc000636008, 0x12ece50, 0xc002574540, 0xc001ed1c80, 0x0, 0x12ece50, 0xc002574540, 0xc001e0d400, 0x39d)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e2420, 0x12f70d8, 0xc000962000, 0xc002d7b300, 0xc00406e5a0, 0x18ae2e0, 0x0, 0x0, 0x0)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/google.golang.org/grpc/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0000e2420, 0x12f70d8, 0xc000962000, 0xc002d7b300, 0x0)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/google.golang.org/grpc/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000342060, 0xc0000e2420, 0x12f70d8, 0xc000962000, 0xc002d7b300)
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/google.golang.org/grpc/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/pcatalini/Documents/terraform/terraform-provider-ns1/vendor/google.golang.org/grpc/server.go:708 +0xa5
FAIL    github.com/terraform-providers/terraform-provider-ns1/ns1       160.290s
FAIL
GNUmakefile:24: recipe for target 'testacc' failed
make: *** [testacc] Error 1`

**Comment by seddarj** [comment]
Regarding vendoring, it's not incompatible with go modules. It's just a way to pin and import your dependencies into your own repository. I saw a `vendor` folder and assumed it was being used. If it's not, I'm happy to add a commit with the result of `git rm -rf vendor` to this PR.

The failing acceptance test is really troublesome though. How should we proceed here? If I make changes and wait for a maintainer to run them every time, it could take a while. Any chance a maintainer can iterate on this and fix the underlying issue?

**Comment by pcatalini** [comment]
@seddarj I'm on it right now

**Comment by pcatalini** [comment]
@seddarj I removed the vendor folder and did go mod tidy and also go mod download, I ran the tests again and everything went well with the new go version. so I suggest removing the vendor and pushing a commit again, then I'll check if nothing is breaking, if you prefer I can open a PR just to remove the vendor

**Comment by seddarj** [comment]
@pcatalini I removed the `vendor` folder in the last commit. We might have to update the Github Action workflows to run `go mod download`. I need an approval for the workflows to run.

**Comment by pcatalini** [comment]
@seddarj I can't approve workflows @Zach-Johnson can help you.
I ran the tests and once again the same error, but the error it's not related to go update, I notice that your branch is out of date, so please rebase your branch with master and the error should be resolved.
One more thing, you can remove the second block of require in go mod since this is just used by vendor

The block to be removed

require (
	cloud.google.com/go v0.45.1 // indirect
	github.com/agext/levenshtein v1.2.2 // indirect
	github.com/apparentlymart/go-cidr v1.0.1 // indirect
	github.com/apparentlymart/go-textseg v1.0.0 // indirect
	github.com/armon/go-radix v1.0.0 // indirect
	github.com/aws/aws-sdk-go v1.25.3 // indirect
	github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d // indirect
	github.com/bgentry/speakeasy v0.1.0 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/fatih/color v1.7.0 // indirect
	github.com/golang/protobuf v1.3.2 // indirect
	github.com/google/go-cmp v0.3.1 // indirect
	github.com/google/uuid v1.1.1 // indirect
	github.com/googleapis/gax-go/v2 v2.0.5 // indirect
	github.com/hashicorp/errwrap v1.0.0 // indirect
	github.com/hashicorp/go-cleanhttp v0.5.1 // indirect
	github.com/hashicorp/go-getter v1.4.0 // indirect
	github.com/hashicorp/go-hclog v0.9.2 // indirect
	github.com/hashicorp/go-multierror v1.0.0 // indirect
	github.com/hashicorp/go-plugin v1.0.1 // indirect
	github.com/hashicorp/go-safetemp v1.0.0 // indirect
	github.com/hashicorp/go-uuid v1.0.1 // indirect
	github.com/hashicorp/go-version v1.2.0 // indirect
	github.com/hashicorp/golang-lru v0.5.1 // indirect
	github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f // indirect
	github.com/hashicorp/hcl/v2 v2.0.0 // indirect
	github.com/hashicorp/logutils v1.0.0 // indirect
	github.com/hashicorp/terraform-config-inspect v0.0.0-20191115094559-17f92b0546e8 // indirect
	github.com/hashicorp/terraform-svchost v0.0.0-20191011084731-65d371908596 // indirect
	github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d // indirect
	github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af // indirect
	github.com/mattn/go-colorable v0.1.1 // indirect
	github.com/mattn/go-isatty v0.0.5 // indirect
	github.com/mitchellh/cli v1.0.0 // indirect
	github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db // indirect
	github.com/mitchellh/copystructure v1.0.0 // indirect
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/mitchellh/go-testing-interface v1.0.0 // indirect
	github.com/mitchellh/go-wordwrap v1.0.0 // indirect
	github.com/mitchellh/mapstructure v1.1.2 // indirect
	github.com/mitchellh/reflectwalk v1.0.1 // indirect
	github.com/oklog/run v1.0.0 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/posener/complete v1.2.1 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/ulikunitz/xz v0.5.5 // indirect
	github.com/vmihailenco/msgpack v4.0.1+incompatible // indirect
	github.com/zclconf/go-cty v1.1.0 // indirect
	github.com/zclconf/go-cty-yaml v1.0.1 // indirect
	go.opencensus.io v0.22.0 // indirect
	golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586 // indirect
	golang.org/x/net v0.0.0-20191009170851-d66e71096ffb // indirect
	golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45 // indirect
	golang.org/x/sys v0.0.0-20190804053845-51ab0e2deafa // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/api v0.9.0 // indirect
	google.golang.org/appengine v1.6.1 // indirect
	google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55 // indirect
	google.golang.org/grpc v1.23.0 // indirect
)

**Comment by seddarj** [comment]
Thanks @pcatalini !

I've merged master into my branch and updated the go.mod file to remove the unnecessary require block. Let's hope this is good now 🤞

**Comment by pcatalini** [comment]
@seddarj now everything is passing! @Zach-Johnson can you double-check and approve to be merged?

**Review by pcatalini — APPROVED** [review]
LGTM

**Comment by Zach-Johnson** [comment]
Hi @seddarj - could you please run a `go mod tidy` on this PR? Other than that I think this is good to go

**Comment by seddarj** [comment]
Hi @Zach-Johnson, it' done in the last commit I just pushed. However, it brings back the second `require` block that @pcatalini said was causing trouble with the tests.

**Comment by Zach-Johnson** [comment]
@seddarj I'm not having an issue with this, I think it's okay. I'm going to merge this. Thanks for your contribution here!

**Comment by Zach-Johnson** [comment]
@seddarj this is released on v1.12.5 now

**Comment by seddarj** [comment]
Thanks @Zach-Johnson & @pcatalini. I can see `darwin_arm64` in the packages for the `1.12.5` release 🎉

**Pull request merged**
