### PR TITLE
DAITDS-250 - Team and user import support added

### PR DESCRIPTION
**Pull request by ThiagoYU**

### CODE REVIEW

**Review by Zach-Johnson — CHANGES_REQUESTED** [review]
Could we add acceptance tests for these? It looks like Terraform supports acceptance testing for imports. I also hit an error case when I imported a user `test-import-user`, where after importing, terraform fails to apply because the `-` in the username fail the regex check we're currently doing. I'm guessing our regex check is out of date, I'm verifying what we can update it to.

**Comment by Zach-Johnson** [comment]
We can use this regex for username matching `^[a-zA-Z0-9@$&'*+\\-=? ^_.{|}~]{3,320}$`

**Comment by ThiagoYU** [comment]
@Zach-Johnson Added import tests and updated the username's regex.

**Review by Zach-Johnson — APPROVED** [review]
nice!

**Pull request merged**
